import streamlit as st
from streamlit_option_menu import option_menu
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import pandas as pd
import json
import os
import datetime

cloud_config= {
  'secure_connect_bundle': 'secure-connect-doanbigdata.zip'
}
# This token JSON file is autogenerated when you download your token, 
# if yours is different update the file name below
token_json = os.getenv("ASTRA_DB_TOKEN")  # Đọc từ GitHub Secrets
if token_json:
    token_data = json.loads(token_json)
else:
    raise ValueError("ASTRA_DB_TOKEN is not set!")

CLIENT_ID = token_data["clientId"]
CLIENT_SECRET = token_data["secret"]

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()


st.title("📊 Hệ thống giám sát ô nhiễm không khí")
st.write("Dữ liệu được lấy từ bảng air_quality trong Cassandra")


selected = option_menu(
    menu_title=None,
    options=["Home", "Data Preview"],
    default_index=0,
    orientation="horizontal",
)

if selected == "Home":
    pass

if selected == "Data Preview":
    st.header("Data Preview")
    query = "SELECT * FROM air_quality LIMIT 200"
    rows = session.execute(query)
    df = pd.DataFrame(rows)
    st.dataframe(df)
